apiVersion: batch/v1
kind: Job
metadata:
  name: command-demo
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: command-demo-container
        image: tarunkumard/fromscratch6.0
        imagePullPolicy: Never
        resources:
          requests:
            memory: "900Mi"
          limits:
            memory: "1Gi"
        env:
        - name: JVM_OPTS
          value: "-Xms900M -Xmx1G"
      restartPolicy: Never