apiVersion: batch/v1
kind: Job
metadata:
  name: command-demo
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
        - name: docker-sock
          emptyDir: {}
      containers:
      - name: command-demo-container
        image: tarunkumard/fromscratch6.0:latest
        volumeMounts:
          - mountPath: /opt/gatling-fundamentals/build/reports/gatling/
            name: docker-sock
      - name: ubuntu
        image: ubuntu:16.04
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 10; done;" ]
        volumeMounts:
          - mountPath: /docker-sock
            name: docker-sock
      restartPolicy: Never