apiVersion: batch/v1
kind: Job
metadata:
  name: command-demo
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: command-demo-container
        image: tarunkumard/fromscratch6.0
        imagePullPolicy: Never
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1Gi"

      - name: ubuntu
        image: ubuntu:16.04
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 10; done;" ]
        imagePullPolicy: Never
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1Gi"
        env:
        - name: JVM_OPTS
          value: "-Xms1G -Xmx1G"
      restartPolicy: Never