apiVersion: batch/v1
kind: Job
metadata:
  name: command-demo
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: command-demo-container
        image: tarunkumard/fromscratch6.0
        
      - name: ubuntu
        image: ubuntu:16.04                        # Run the ubuntu 16.04
        command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
        args: [ "while true; do sleep 10; done;" ] # Our simple program just sleeps inside an infinite loop
      restartPolicy: Never